package com.java2024.ecoscape.models;

public enum Amenity {
    HAS_FRIDGE,
    HAS_DISHWASHER,
    HAS_WASHING_MACHINE,
    HAS_STOVE,
    HAS_MICROWAVE,
    HAS_WIFI,
    HAS_TV,
    HAS_PARKING,
    HAS_KITCHEN,
    HAS_CRIB,
    HAS_BABY_CHAIR,
    HAS_BICYCLE,
    HAS_FIRE_ALARM,
    HAS_BREAKFAST_INCLUDED,
    HAS_ACCESSIBILITY,
    HAS_ELECTRICITY_VEHICLE_CHARGE,
    IS_PET_FRIENDLY
    }
