package com.java2024.ecoscape.models;

public enum Category {
    ECO_LODGE,
    GLAMPING,
    CULTURAL_STAY,
    NATIONAL_PARK,
    WILDLIFE_RETREAT,
    WELLNESS_RETREAT,
    TINY_HOME,
    TREE_HOUSE,
    MOUNTAIN_RETREAT,
    FARM_STAY,
    WHEELCHAIR_FRIENDLY,
    BABY_FRIENDLY,
    PET_FRIENDLY
    }
