package com.java2024.ecoscape.models;

public enum Sustainability {
    RENEWABLE_ENERGY,
    CAR_FREE,
    ECO_CLEANING,
    WASTE_RECYCLE,
    ENERGY_SAVING_LIGHTS,
    GREEN_BUILDING,
    SOLAR_PANELS,
    WATER_FLOW_REDUCER,
    RECOVER_REUSE_RAINWATER,
    TOWEL_CHANGE_REQUEST,
    APPLIANCES_CLASS_A,
    HIGH_EFFICIENCY_BOILER,
    ENVIRONMENTAL_FRIENDLY_FURNITURE,
    BIODIVERSITY

    }
